[profile.default]
src = "src/foundry-contracts"
out = "out"
libs = ["node_modules", "lib"]
remappings = ["@contracts=src/foundry-contracts"]
verbosity = 4
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
